<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.ujorm</groupId>
    <artifactId>ujorm-meta-processor</artifactId>
    <version>3.0.0-BETA</version>
    <packaging>jar</packaging>
    <name>ujorm-meta-processor</name>
    <description>Generates metamodel from entities during the compilation phase using APT.</description>
    <url>https://ujorm.org/www/web/index.html</url> <!-- home page -->

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>pponec</id>
            <name>PPonec</name>
            <email>pponec@gmail.com</email>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/pponec/ujorm.git</url>
        <connection>scm:git:git@github.com/pponec/ujorm.git</connection>
        <developerConnection>scm:git:git@github.com/pponec/ujorm.git</developerConnection>
    </scm>

    <properties>
        <revision>3.0.0-BETA</revision>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <!-- Prevents an error when compiling APT itself -->
                    <compilerArgument>-proc:none</compilerArgument>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>