<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>9</version>
    </parent>

    <groupId>org.ujorm</groupId>
    <artifactId>main</artifactId>
    <version>3.0.1</version>
    <name>Main UJO</name>
    <packaging>pom</packaging>
    <description>Ujorm common project</description>

    <properties>
        <revision>3.0.1</revision>
        <java.version>17</java.version>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.12.2</junit.version>
        <jakarta.persistence.version>3.1.0</jakarta.persistence.version>
        <lombok.version>1.18.42</lombok.version>
        <skipITs>true</skipITs>
    </properties>

    <modules>
        <module>project-m2</module>
        <module>ujorm3-integration-tests</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.ujorm</groupId>
                <artifactId>ujo-tools</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.ujorm</groupId>
                <artifactId>ujo-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.ujorm</groupId>
                <artifactId>ujo-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.ujorm</groupId>
                <artifactId>ujo-orm</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.ujorm</groupId>
                <artifactId>ujo-converter</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>21.0.1</version>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <scm>
        <url>http://sourceforge.net/p/ujoframework/svn/HEAD/tree/trunk/</url>
        <connection>scm:svn:https://ujoframework.svn.sourceforge.net/svnroot/ujoframework/trunk</connection>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <properties>
                        <includeTags>junit5</includeTags>
                    </properties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.2.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skipITs>${skipITs}</skipITs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>common</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>

        <profile>
            <id>production</id>
        </profile>

        <profile>
            <id>docker-it</id>
            <properties>
                <skipITs>false</skipITs>
            </properties>
        </profile>
    </profiles>

</project>