package org.ujorm.orm.tutorial;

import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.ujorm.orm.SqlQuery;

/** Oracle integration test implementation */
@Testcontainers
class OracleTutorialIT extends AbstractTutorialIT {

    /** Oracle Free container */
    @Container
    @ServiceConnection
    static OracleContainer oracle = new OracleContainer("gvenzl/oracle-free:23-slim-faststart");

    @Override
    void init() {
        try (var query = new SqlQuery(connection())) {
            query.sql("""
                    CREATE TABLE city
                    ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    , name VARCHAR2(50) NOT NULL
                    , country_code VARCHAR2(2) NOT NULL
                    )
                    """).execute();
            query.sql("""
                    CREATE TABLE employee
                    ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                    , name VARCHAR2(50) NOT NULL
                    , boss_id NUMBER NULL
                    , city_id NUMBER NOT NULL
                    )
                    """).execute();
            query.sql("""
                    ALTER TABLE employee ADD CONSTRAINT fk_employee_boss_id__id
                    FOREIGN KEY (boss_id)
                    REFERENCES employee(id)
                    """).execute(); // Oracle implicitly takes ON DELETE RESTRICT
            query.sql("""
                    ALTER TABLE employee ADD CONSTRAINT fk_employee_city_id__id
                    FOREIGN KEY (city_id)
                    REFERENCES city(id)
                    ON DELETE CASCADE
                    """).execute();
        }
    }
}