package org.ujorm.mapper;

import org.ujorm.tools.msg.MessageService;

import java.io.StringWriter;
import java.util.HashMap;

public class JavaSourceGenerator {

    private final String PACKAGE_PREFIX = "org.ujorm.gen_.";

    public String getSourceCode(DomainModel meta) {
        var writer = new StringWriter(256);
        var record = meta.domainClass().isRecord();
        var params = new HashMap<String, Object>();
        {
            params.put("package", PACKAGE_PREFIX + meta.domainClass().getPackageName());
            params.put("generatedClass", meta.domainClass().getSimpleName() + "_");
            params.put("domainType", meta.domainClass().getName());
            params.put("generatorClass", getClass().getSimpleName());
            params.put("generatorPackage", getClass().getPackageName());
        }
        var templateBeg1 = """
                package ${package};
                import org.jetbrains.annotations.NotNull;
                import org.jetbrains.annotations.Nullable;
                import org.ujorm.core.Key;
                import org.ujorm.core.impl.AbstractKey;
                import org.ujorm.core.impl.AbstractMetaModel;
                
                /** This class was generated by ${generatorClass} from the ${generatorPackage} package. */
                public class ${generatedClass} extends AbstractMetaModel<${domainType}> {
                private static final Class<${domainType}> domainType = ${domainType}.class;
                public ${generatedClass}() {
                """;
            //  super( new Key_id(0)
            //       , new Key_name(1)
        var templateBeg2 = """
                     );
                }
                @Override
                public ${domainType} newDomain(@NotNull final Object... values) {
                """;
        var templateBeg3bean = """
                final var result = new ${domainType}();
                for (int i = 0, max = Math.min(values.length, keyList.size()); i < max; i++) {
                    final var key = (Key<${domainType}, Object>) keyList.get(i);
                    key.setValue(result, values[i]);
                }
                return result;
                """.indent(4);
        var templateBeg4 = """
                }
                @NotNull
                public Class<${domainType}> getDomainType() {
                    return domainType;
                }
                """;
        var templateKey = """           
                /** Key ${propName} */
                static final class Key_${propName} extends AbstractKey<${domainType}, ${propObjectType}> {
                    public Key_${propName}(final int order) {
                        super(order, "${propName}", ${propType}.class, "${column}", ${primaryKey}, ${required});
                    }
                    @Override
                    public void setValue(@NotNull final ${domainType} bean, @Nullable final ${propObjectType} value) {
                        bean.${setter}(value != null ? value : defaultValue);
                    }
                    @Override
                    public ${propObjectType} getValue(@NotNull final ${domainType} bean) {
                        return bean.${getter}();
                    }
                    @Override
                    public @NotNull Class<${domainType}> getDomainType() {
                        return domainType;
                    }
                }
                """;
        var templateEnd = "}";

        MessageService.formatMsg(templateBeg1, params, writer);
        buildConstructor(meta, writer);
        MessageService.formatMsg(templateBeg2, params, writer);
        MessageService.formatMsg(templateBeg3bean, params, writer);
        MessageService.formatMsg(templateBeg4, params, writer);
        buildInnerKeys(templateKey, meta, writer);
        MessageService.formatMsg(templateEnd, params, writer);
        return writer.toString();
    }

    private void buildConstructor(DomainModel meta, StringWriter writer) {
        for(int i = 0, max = meta.properties().size(); i < max; ++i) {
            var row = (i == 0)
                    ? "super( new Key_%s(%s)"
                    : "     , new Key_%s(%s)";
            writer.append("    ")
                  .append(row.formatted(meta.properties().get(i).propertyName(), i))
                  .append("\n");
        }
    }

    private void buildInnerKeys(String template, DomainModel meta, StringWriter writer) {
        final var params = new HashMap<String, Object>();
        for (var prop: meta.properties()) {
            {
                params.put("propName", prop.propertyName());
                params.put("propType", prop.propertyType().getName());
                params.put("propObjectType", prop.propertyObjectType().getName());
                params.put("getter", prop.getter());
                params.put("setter", prop.setter());
                params.put("primaryKey", prop.primaryKey());
                params.put("required", prop.required());
                params.put("column", prop.dbColumName());

                params.put("domainType", meta.domainClass().getName());
            }
            MessageService.formatMsg(template, params, writer);
        }
    }
}
