package org.ujorm.mapper.impl;

import java.util.Properties;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Tests for the ConfigImpl class. */
class ConfigImplTest {

    /** Inner class for mocking properties without external file dependency. */
    static class ConfigImplMock extends ConfigImpl {
        @Override
        protected Properties properties() {
            var props = new Properties();
            props.setProperty("org.ujorm.maxCacheSize", "1024");
            props.setProperty("org.ujorm.printSql", "false");
            props.setProperty("org.ujorm.batchSize", "128");
            return props;
        }
    }

    @AfterEach
    void tearDown() {
        // Cleanup of system properties to prevent affecting other tests
        System.clearProperty("org.ujorm.batchSize");
        System.clearProperty("org.ujorm.printSql");
        System.clearProperty("org.ujorm.maxCacheSize");
    }

    @Test
    void testLoadFromFile() {
        // Verifies actual loading from the ujorm-config.properties file
        var config = new ConfigImpl();
        assertEquals("fileValue", config.getTestOnly());
    }

    @Test
    void testMockedProperties() {
        // Verifies standard loading from a properties object (file simulation)
        var config = new ConfigImplMock();

        assertEquals(1024, config.getMaxCacheSize());
        assertFalse(config.isPrintSql());
        assertEquals(128, config.getBatchSize());
        assertTrue(config.isFirstPropertyIsIdentifier()); // Remains default
    }

    @Test
    void testSystemPropertyPriority() {
        // System property must take precedence over the properties file
        System.setProperty("org.ujorm.batchSize", "2048");
        System.setProperty("org.ujorm.printSql", "true"); // Originally false in the mock

        var config = new ConfigImplMock();

        assertEquals(2048, config.getBatchSize(), "System property must override the int value from properties.");
        assertTrue(config.isPrintSql(), "System property must override the boolean value from properties.");
    }

    @Test
    void testInvalidSystemPropertyConversion() {
        System.setProperty("org.ujorm.maxCacheSize", "not_a_number");
        var exception = assertThrows(
                NumberFormatException.class,
                ConfigImplMock::new
        );
        assertTrue(exception.getMessage().contains("not_a_number"));
    }

    @Test
    void testBuilderOverrides() {
        // Verifies the Lombok Builder functionality for easy configuration adjustments
        var config = ConfigImpl.builderWithDefaults()
                .maxCacheSize(9999)
                .printSql(false)
                .testOnly("BUILDER_TEST")
                .build();

        assertEquals(9999, config.getMaxCacheSize());
        assertFalse(config.isPrintSql());
        assertEquals("BUILDER_TEST", config.getTestOnly());

        // The rest must remain preserved from the default values
        assertTrue(config.isFirstPropertyIsIdentifier());
    }

    @Test
    void testValueMethodWithNullDefaultThrowsException() {
        var config = new ConfigImplMock();
        var emptyProperties = new Properties();

        // Expecting IllegalArgumentException generated by JetBrains @NotNull instrumentation
        var exception = assertThrows(
                IllegalArgumentException.class,
                () -> config.value(null, "someKey", emptyProperties),
                "The value() method must throw an exception if defaultValue is null."
        );

        // Check that the error message contains 'defaultValue'
        assertTrue(
                exception.getMessage().contains("defaultValue"),
                "The error message should specify that the problem is in the defaultValue parameter."
        );
    }

    @Test
    void testUnsupportedTypeConversion() {
        var config = new ConfigImplMock();

        // Verifies that converting an unsupported type throws an IllegalStateException
        var exception = assertThrows(
                IllegalStateException.class,
                () -> config.convertValue("someValue", java.util.Date.class),
                "Should throw an exception for unsupported types."
        );

        assertTrue(exception.getMessage().contains("Can't convert value"));
    }
}