/*
 * Copyright 2026-2026 Pavel Ponec
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ujorm.core.generator;

import org.ujorm.core.impl.AbstractDomainHandler;
import org.ujorm.core.impl.AbstractKey;
import org.ujorm.tools.msg.MessageService;

import java.util.HashMap;

/**
 * A domain-driven source code generator targeting Java 17+ for {@code Record} or {@code Bean} objects.
 * <p>
 * This class transforms domain-specific metadata into valid source files,
 * supporting both modern immutable structures (records) and traditional mutable patterns (beans).
 */
public class JavaSourceGenerator {
    /**
     * Enable jetbrains annotations.
     * Value true enforces a runtime dependency on the Jetbrains annotations library.
     */
    final boolean enableEnotations = false;

    public String getSourceCode(DomainModel meta, ClassName className) {
        checkProperties(meta);
        final var writer = new StringBuilder(5_000);
        final var params = new HashMap<String, Object>(20);
        {
            params.put("package", className.packageName());
            params.put("generatedClass", className.className());
            params.put("domainClass", meta.domainClass().getSimpleName());
            params.put("domainClassFull", meta.domainClass().getCanonicalName());
            params.put("baseClass", AbstractDomainHandler.class.getSimpleName());
            params.put("baseClassFull", AbstractDomainHandler.class.getCanonicalName());
            params.put("baseKeyClass", AbstractKey.class.getSimpleName());
            params.put("baseKeyClassFull", AbstractKey.class.getCanonicalName());
            params.put("generatorClass", getClass().getSimpleName());
            params.put("generatorPackage", getClass().getPackageName());
            params.put("@NotNull", enableEnotations ? "@org.jetbrains.annotations.NotNull" : "");
            params.put("@Nullable", enableEnotations ? "@org.jetbrains.annotations.Nullable" : "");
        }
        var templateBeg1 = """
                package ${package};
                import ${baseClassFull};
                import ${baseKeyClassFull};
                import ${domainClassFull};
                
                /** This class was generated by ${generatorClass} from the ${generatorPackage} package. */
                public final class ${generatedClass} extends ${baseClass}<${domainClass}> {
                private static final Class<${domainClass}> domainClass = ${domainClass}.class;
                public ${generatedClass}() {
                """;
        //  super( new Key_id(0)
        //       , new Key_name(1)
        var templateBeg2 = """
                     );
                }
                @Override @SuppressWarnings("unchecked")
                public ${domainClass} newDomain(${@NotNull} Object... values) {
                """;
        var templateBeg3bean = """
                final var result = new ${domainClass}();
                for (int i = 0, max = Math.min(values.length, keyList.size()); i < max; i++) {
                    final var key = (${baseKeyClass}<${domainClass}, Object>) keyList.get(i);
                    key.setValue(result, values[i]);
                }
                return result;
                """.indent(4);
        var templateBeg4 = """
                }
                ${@NotNull}
                public Class<${domainClass}> getDomainClass() {
                    return domainClass;
                }
                """;
        var templateKey = """
                /** Key ${propName} */
                static final class Key_${propName} extends ${baseKeyClass}<${domainClass}, ${propObjectType}> {
                    public Key_${propName}(final int order) {
                        super(order, "${propName}", ${propType}.class, "${column}", ${primaryKey}, ${foreignKey}, ${required}, ${mapEnumByOrdinal});
                    }
                    @Override
                    public void setValue(${@NotNull} final ${domainClass} bean, ${@Nullable} final ${propObjectType} value) {
                        %s;
                    }
                    @Override
                    public ${propObjectType} getValue(${@NotNull} final ${domainClass} bean) {
                        return bean.${getter}();
                    }
                    @Override
                    public boolean writable() {
                        return ${writable};
                    }
                    @Override
                    public ${@NotNull} Class<${domainClass}> domainClass() {
                        return domainClass;
                    }
                }
                """;
        var templateEnd = "}";

        MessageService.formatMsg(templateBeg1, params, writer);
        buildConstructor(meta, writer);
        MessageService.formatMsg(templateBeg2, params, writer);
        if (meta.isRecord()) {
            buildRecordConstructorBuilder(meta, params.get("domainClass"), writer);
        } else {
            MessageService.formatMsg(templateBeg3bean, params, writer);
        }
        MessageService.formatMsg(templateBeg4, params, writer);
        buildInnerKeys(templateKey, meta, writer, params);
        MessageService.formatMsg(templateEnd, params, writer);
        return writer.toString();
    }

    private void buildConstructor(DomainModel meta, StringBuilder writer) {
        for(int i = 0, max = meta.properties().size(); i < max; ++i) {
            var row = (i == 0)
                    ? "super( new Key_%s(%s)"
                    : "     , new Key_%s(%s)";
            writer.append("    ")
                  .append(row.formatted(meta.properties().get(i).name(), i))
                  .append("\n");
        }
    }

    private void buildInnerKeys(String template, DomainModel meta, StringBuilder writer, HashMap<String, Object> params) {
        for (var prop: meta.properties()) {
            {
                params.put("propName", prop.name());
                params.put("propType", prop.type().getCanonicalName());
                params.put("propObjectType", prop.propertyObjectType().getCanonicalName());
                params.put("getter", prop.getter());
                params.put("primaryKey", prop.primaryKey());
                params.put("foreignKey", prop.foreignKey());
                params.put("required", prop.required());
                params.put("writable", prop.isWritable());
                params.put("column", prop.dbColumName());
                params.put("mapEnumByOrdinal", prop.mapEnumByOrdinal());
            }
            MessageService.formatMsg(template.formatted(buildSetterBody(prop)), params, writer);
        }
    }

    /**
     * An empty model would generate an uncompilable source code, whose failure names the generated
     * class rather than the real cause, so the domain class is reported here instead.
     *
     * @throws IllegalArgumentException The domain class has no mapped property.
     */
    private void checkProperties(DomainModel meta) {
        if (meta.properties().isEmpty()) {
            throw new IllegalArgumentException(("The class %s has no mapped property."
                    + " A domain object needs at least one field with a getter, which is excluded"
                    + " neither by the @Transient annotation nor by the transient modifier.")
                    .formatted(meta.domainClass().getSimpleName()));
        }
    }

    /** Body of the {@code setValue()} method. A property without a setter is assigned by a constructor only. */
    private String buildSetterBody(DomainPropertyModel prop) {
        return prop.isWritable()
                ? "bean.%s(value != null ? value : defaultValue)".formatted(prop.setter())
                : "throw unsupportedSetter(this)";
    }

    /** Build a call of the canonical constructor.
     * The arguments are taken from the record components rather than from the domain properties,
     * because a component excluded from the model (a transient one) must keep its position.
     * <p>The excluded component gets a hard-coded default, so its value is lost whenever the ORM
     * builds the record - not only on a database read. The entity returned by {@code Crud.insert()}
     * is rebuilt here to carry the generated primary key, hence it comes back with the excluded
     * component reset, while the object passed by the caller stays untouched. Carrying the value
     * through would require the source record as another argument of the factory method. */
    private void buildRecordConstructorBuilder(DomainModel meta, Object domainClass, StringBuilder writer) {
        var offset1 = " ".repeat(4);
        var offset2 = " ".repeat(9);
        var valueIndexes = new HashMap<String, Integer>(meta.properties().size());
        for (int i = 0, max = meta.properties().size(); i < max; ++i) {
            valueIndexes.put(meta.properties().get(i).name(), i);
        }
        var components = meta.domainClass().getRecordComponents();
        writer.append(offset1).append("values = normalizePrimitives(values);\n");
        writer.append(offset1).append("return new ").append(domainClass).append("\n");
        for (int i = 0; i < components.length; ++i) {
            var sep = (i == 0) ? "( " : ", ";
            var valueIndex = valueIndexes.get(components[i].getName());
            var row = valueIndex != null
                    ? "(%s) values[%s]\n".formatted(
                            meta.properties().get(valueIndex).propertyObjectType().getCanonicalName(), valueIndex)
                    : "%s // The component is out of the domain model\n".formatted(defaultValueCode(components[i].getType()));
            writer.append(offset2).append(sep).append(row);
        }
        writer.append(offset2).append(");\n");
    }

    /** Source code of a default value for a record component missing in the domain model. */
    private String defaultValueCode(Class<?> componentType) {
        if (!componentType.isPrimitive()) {
            return "(%s) null".formatted(componentType.getCanonicalName());
        }
        return componentType == boolean.class
                ? "false"
                : "(%s) 0".formatted(componentType.getName());
    }
}