package org.ujorm.mapper.generator;

import org.ujorm.mapper.core.impl.AbstractDomainHandler;
import org.ujorm.mapper.core.impl.AbstractKey;
import org.ujorm.mapper.DomainHandlerService;
import org.ujorm.tools.msg.MessageService;

import java.io.StringWriter;
import java.util.HashMap;

/**
 * A domain-driven source code generator targeting Java 17+ for {@code Record} or {@code Bean} objects.
 * <p>
 * This class transforms domain-specific metadata into valid source files,
 * supporting both modern immutable structures (records) and traditional mutable patterns (beans).
 */
public class JavaSourceGenerator {

    public String getSourceCode(DomainModel meta, ClassName className) {
        final var writer = new StringWriter(5_000);
        final var params = new HashMap<String, Object>(20);
        {
            params.put("package", className.packageName());
            params.put("generatedClass", className.className());
            params.put("domainClass", meta.domainClass().getSimpleName());
            params.put("domainClassFull", meta.domainClass().getName());
            params.put("baseClass", AbstractDomainHandler.class.getSimpleName());
            params.put("baseClassFull", AbstractDomainHandler.class.getName());
            params.put("baseKeyClass", AbstractKey.class.getSimpleName());
            params.put("baseKeyClassFull", AbstractKey.class.getName());
            params.put("generatorClass", getClass().getSimpleName());
            params.put("generatorPackage", getClass().getPackageName());
        }
        var templateBeg1 = """
                package ${package};
                import org.jetbrains.annotations.NotNull;
                import org.jetbrains.annotations.Nullable;
                import ${baseClassFull};
                import ${baseKeyClassFull};
                import ${domainClassFull};
                
                /** This class was generated by ${generatorClass} from the ${generatorPackage} package. */
                public final class ${generatedClass} extends ${baseClass}<${domainClass}> {
                private static final Class<${domainClass}> domainClass = ${domainClass}.class;
                public ${generatedClass}() {
                """;
            //  super( new Key_id(0)
            //       , new Key_name(1)
        var templateBeg2 = """
                     );
                }
                @Override
                public ${domainClass} newDomain(@NotNull Object... values) {
                """;
        var templateBeg3bean = """
                final var result = new ${domainClass}();
                for (int i = 0, max = Math.min(values.length, keyList.size()); i < max; i++) {
                    final var key = (${baseKeyClass}<${domainClass}, Object>) keyList.get(i);
                    key.setValue(result, values[i]);
                }
                return result;
                """.indent(4);
        var templateBeg4 = """
                }
                @NotNull
                public Class<${domainClass}> getDomainClass() {
                    return domainClass;
                }
                """;
        var templateKey = """           
                /** Key ${propName} */
                static final class Key_${propName} extends ${baseKeyClass}<${domainClass}, ${propObjectType}> {
                    public Key_${propName}(final int order) {
                        super(order, "${propName}", ${propType}.class, "${column}", ${primaryKey}, ${required});
                    }
                    @Override
                    public void setValue(@NotNull final ${domainClass} bean, @Nullable final ${propObjectType} value) {
                        %s;
                    }
                    @Override
                    public ${propObjectType} getValue(@NotNull final ${domainClass} bean) {
                        return bean.${getter}();
                    }
                    @Override
                    public @NotNull Class<${domainClass}> getDomainClass() {
                        return domainClass;
                    }
                }
                """.formatted(meta.isRecord()
                    ? "throw unsupportedSetter(this)"
                    : "bean.${setter}(value != null ? value : defaultValue)");
        var templateEnd = "}";

        MessageService.formatMsg(templateBeg1, params, writer);
        buildConstructor(meta, writer);
        MessageService.formatMsg(templateBeg2, params, writer);
        if (meta.isRecord()) {
            buildRecordConstructorBuilder(meta, params.get("domainClass"), writer);
        } else {
            MessageService.formatMsg(templateBeg3bean, params, writer);
        }
        MessageService.formatMsg(templateBeg4, params, writer);
        buildInnerKeys(templateKey, meta, writer, params);
        MessageService.formatMsg(templateEnd, params, writer);
        return writer.toString();
    }

    private void buildConstructor(DomainModel meta, StringWriter writer) {
        for(int i = 0, max = meta.properties().size(); i < max; ++i) {
            var row = (i == 0)
                    ? "super( new Key_%s(%s)"
                    : "     , new Key_%s(%s)";
            writer.append("    ")
                  .append(row.formatted(meta.properties().get(i).propertyName(), i))
                  .append("\n");
        }
    }

    private void buildInnerKeys(String template, DomainModel meta, StringWriter writer, HashMap<String, Object> params) {
        for (var prop: meta.properties()) {
            {
                params.put("propName", prop.propertyName());
                params.put("propType", prop.propertyType().getName());
                params.put("propObjectType", prop.propertyObjectType().getName());
                params.put("getter", prop.getter());
                params.put("setter", prop.setter());
                params.put("primaryKey", prop.primaryKey());
                params.put("required", prop.required());
                params.put("column", prop.dbColumName());
            }
            MessageService.formatMsg(template, params, writer);
        }
    }

    private void buildRecordConstructorBuilder(DomainModel meta, Object domainClass, StringWriter writer) {
        var offset1 = " ".repeat(4);
        var offset2 = " ".repeat(9);
        writer.append(offset1).append("values = normalizePrimitives(values);\n");
        writer.append(offset1).append("return new ").append(String.valueOf(domainClass)).append("\n");
        for(int i = 0, max = meta.properties().size(); i < max; ++i) {
            var sep = (i == 0) ? "( " : ", ";
            var type = meta.properties().get(i).propertyObjectType().getName();
            var row = "(%s) values[%s]\n".formatted(type, i);
            writer.append(offset2).append(sep).append(row);
        }
        writer.append(offset2).append(");\n");
    }
}
