package org.ujorm.metamodel;

import java.time.LocalDateTime;
import javax.annotation.Nullable;
import org.ujorm.Key;
import org.ujorm.core.AbstractKey;
import org.ujorm.core.MetaInterface;
import org.ujorm.core.UjoContext;
import org.ujorm.doman.*;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class MetaUser<D> extends AbstractKey<D, User> implements MetaInterface<D> {

    public MetaUser(Class<D> domainClass, UjoContext context) {
        super(domainClass, context);
    }

    public Key<D, Integer> keyId() {
        return null;
    }

    public Key<D, Short> pin() {
        return null;
    }

    public Key<D, String> firstName() {
        return null;
    }

    public Key<D, String> sureName() {
        return null;
    }

    public Key<D, LocalDateTime> created() {
        return null;
    }

    public Key<D, MetaUser> parent() {
        return null;
    }

    @Override
    public D newDomain() {
        return (D) new User();
    }

    public static final MetaUser<User> of(@Nullable UjoContext context) {
        return context.getMetaModel(User.class, MetaUser.class);
    }

    public static final MetaUser<User> of() {
        return of(UjoContext.of());
    }

}
