package org.ujorm.metamodel;

import java.time.LocalDateTime;
import javax.annotation.Nullable;
import org.ujorm.Key;
import org.ujorm.core.AbstractKey;
import org.ujorm.core.MetaInterface;
import org.ujorm.core.UjoContext;
import org.ujorm.doman.*;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class MetaUser<T> extends AbstractKey<T, User> implements MetaInterface<T> {

    public MetaUser(Class<T> domainClass, UjoContext context) {
        super(domainClass, context);
    }

    public Key<T, Integer> keyId() {
        return null;
    }

    public Key<T, Short> pin() {
        return null;
    }

    public Key<T, String> firstName() {
        return null;
    }

    public Key<T, String> sureName() {
        return null;
    }

    public Key<T, LocalDateTime> created() {
        return null;
    }

    public Key<T, MetaUser> parent() {
        return null;
    }

    @Override
    public T newDomain() {
        return (T) new User();
    }

    public static final MetaUser<User> of(@Nullable UjoContext context) {
        return context.getMetaModel(User.class, MetaUser.class);
    }

    public static final MetaUser<User> of() {
        return of(UjoContext.of());
    }

}
