package org.ujorm.orm.tutorial;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.ujorm.orm.SqlQuery;
import org.ujorm.orm.jdbc.ResultSetMapper;
import org.ujorm.orm.tutorial.domains.City;
import org.ujorm.orm.tutorial.domains.MetaCity;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * <strong>Quick Start Tutorial: Low-level SQL with Ujorm</strong>
 *
 * <p>
 * This class demonstrates how to use the {@link SqlQuery} for direct database access
 * while maintaining type safety and performance. Key features for beginners:
 * </p>
 *
 * <ul>
 *   <li><strong>SQL Templates:</strong> Use <code>${c.id}</code> syntax to bind column names
 *       to Meta-model constants, preventing typos and hardcoded strings.</li>
 *   <li><strong>Named Parameters:</strong> Use <code>:id</code> syntax for safe
 *       parameter binding, preventing SQL injection.</li>
 *   <li><strong>Resource Efficiency:</strong> Reusing the {@link SqlQuery} instance
 *       is highly efficient as it maintains a single internal PreparedStatement.</li>
 *   <li><strong>Meta Classes:</strong> Classes with the <strong>Meta</strong> prefix (e.g., MetaCity)
 *       are generated by Ujorm. While they provide type-safe column names, they are
 *   <strong>optional</strong>; you can also use standard Java property names for SELECT mapping.</li>
 * </ul>
 *
 * Note: Tests are ordered to follow a logical database lifecycle.
 *
 * @see City The immutable Java Record used as a data carrier.
 * @see MetaCity The generated Meta-model for type-safe database interaction.
 * @see TutorialTest Extended examples using the {@link org.ujorm.orm.dsl.SelectQuery} class.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class QuickStartTutorialTest extends AbstractDemo {

    private static final ResultSetMapper<City> CITY_MAPPER = ResultSetMapper.of(City.class);

    private City cityOttawa = new City(1L, "Ottawa", "CA");
    private City cityBarcelona = new City(2L, "Barcelona", "ES");

    /** Demonstrate record insertion with PreparedStatement reuse. */
    @Test
    @Order(100)
    void insert() {
        try (var query = new SqlQuery(connection())) {
            query.sql("""
                             INSERT INTO city
                             ( id,  name,  country_code) VALUES 
                             (:id, :name, :countryCode )
                            """)
                    .bind("id", cityOttawa.id())
                    .bind("name", cityOttawa.name())
                    .bind("countryCode", cityOttawa.countryCode())
                    .execute();

            // --- Reuse the same query instance with other parameters ---

            query.bind("id", cityBarcelona.id())
                    .bind("name", cityBarcelona.name())
                    .bind("countryCode", cityBarcelona.countryCode())
                    .execute();
        }
    }

    /** Select cities using Meta-model templates and type-safe result mapping. */
    @Test
    @Order(200)
    void select() {
        try (var query = new SqlQuery(connection())) {
            var cities = query.sql("""
                            SELECT c.id      AS ${c.id}
                            , c.name         AS ${c.name}
                            , c.country_code AS ${c.countryCode}
                            FROM city c
                            WHERE c.id >= :id
                            """)
                    .label("c.id", MetaCity.id)
                    .label("c.name", MetaCity.name)
                    .label("c.countryCode", MetaCity.countryCode)
                    .bind("id", 1L)
                    .streamMap(rs -> new City(
                            rs.getLong(MetaCity.id.name()),
                            rs.getString(MetaCity.name.name()),
                            rs.getString(MetaCity.countryCode.name())))
                    .toList();

            assertEquals(2, cities.size());

            // --- Reuse the query with the sophisticated ResultSetMapper ---

            var nextCities = query.bind("id", 2L)
                    .streamMap(CITY_MAPPER.mapper())
                    .toList();
            assertEquals(1, nextCities.size());
        }
    }

    /** Initialize the database schema for the City entity. */
    @Override
    void init() {
        try (var query = new SqlQuery(connection())) {
            query.sql("""
                            CREATE TABLE city
                            ( id BIGINT AUTO_INCREMENT PRIMARY KEY
                            , name VARCHAR(50) NOT NULL
                            , country_code VARCHAR(2) NOT NULL
                            )
                            """)
                    .execute();
        }
    }
}