package org.ujorm2.metamodel;

import java.math.BigDecimal;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import org.ujorm2.Key;
import org.ujorm2.core.AbstractDomainModel;
import org.ujorm2.core.DirectKeyRing;
import org.ujorm2.core.KeyFactory;
import org.ujorm2.core.XKey;
import org.ujorm2.doman.Item;
import org.ujorm2.doman.Order;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 * @param <D> Domain
 */
public class _Item<D> extends AbstractDomainModel<D, Item> {

    /** All direct directKeys */
    static final class DirectKeys<T extends Item> extends DirectKeyRing<T> {

        final KeyFactory<T> keyFactory = new KeyFactory(Item.class);

        final XKey<Integer> id = keyFactory.newKey(
                (d) -> d.getId(),
                (d, v) -> d.setId(v));

        final XKey<String> note = keyFactory.newKey(
                (d) -> d.getNote(),
                (d, v) -> d.setNote(v));

        final XKey<BigDecimal> price = keyFactory.newKey(
                (d) -> d.getPrice(),
                (d, v) -> d.setPrice(v));

        final XKey<Order> order = keyFactory.newKey(
                (d) -> d.getOrder(),
                (d, v) -> d.setOrder(v));

        final XKey<Boolean> descending = keyFactory.newKey(
                (d) -> d.getDescending(),
                (d, v) -> d.setDescending(v));

        final XKey<Integer> codePoints = keyFactory.newKey(
                (d) -> d.getCodePoints(),
                (d, v) -> d.setCodePoints(v));

        @Override
        public KeyFactory<T> getKeyFactory() {
            return keyFactory;
        }
    };

    public _Item() {
        super(new DirectKeys());
    }

    public _Item(@Nullable final Key<D, ?> keyPrefix, @Nonnull final DirectKeyRing directKeyRing, final boolean descending) {
        super(keyPrefix, directKeyRing, descending);
    }

    @Override
    public <A> AbstractDomainModel<A, Item> prefix(Key<A, D> key) {
        return new _Item(key, directKeys(), false);
    }

    @Override
    public D createDomain() {
        return (D) new Item();
    }

    /** Provider of an instance of DirectKeys */
    @Override
    protected final DirectKeys directKeys() {
        return (DirectKeys) directKeyRing;
    }

    // --- KEY PROVIDERS ---

    public Key<D, Integer> id() {
        return getKey(directKeys().id);
    }

    public Key<D, String> note() {
        return getKey(directKeys().note);
    }

    public Key<D, BigDecimal> price() {
        return getKey(directKeys().price);
    }

    public _Order<D> order() {
        return (_Order) getKey(directKeys().order);
    }

    public Key<D, Boolean> descending$() {
        return getKey(directKeys().descending);
    }

    public Key<D, Integer> codePoints$() {
        return getKey(directKeys().codePoints);
    }

    // ---- Helper method

    public static final _Item<Item> of(@Nullable KeyFactory context) {
        return new _Item<>();
    }

}
