package org.ujorm2.metamodel;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import org.ujorm2.Key;
import org.ujorm2.core.AbstractDomainModel;
import org.ujorm2.core.DirectKeyRing;
import org.ujorm2.core.KeyFactory;
import org.ujorm2.core.XKey;
import org.ujorm2.doman.Order;
import org.ujorm2.doman.Order.State;
import org.ujorm2.doman.User;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class _Order<D> extends AbstractDomainModel<D, Order> {

    /** All direct directKeys */
    static final class DirectKeys<T extends Order> extends DirectKeyRing<T> {

        final KeyFactory<T> keyFactory = new KeyFactory(Order.class);

        final XKey<Integer> id = keyFactory.newKey(
                (d) -> d.getId(),
                (d, v) -> d.setId(v));

        final XKey<State> state = keyFactory.newKey(
                (d) -> d.getState(),
                (d, v) -> d.setState(v));

        final XKey<BigDecimal> totalPrice = keyFactory.newKey(
                (d) -> d.getTotalPrice(),
                (d, v) -> d.setTotalPrice(v));

        final XKey<User> user = keyFactory.newKey(
                (d) -> d.getUser(),
                (d, v) -> d.setUser(v));

        final XKey<String> note = keyFactory.newKey(
                (d) -> d.getNote(),
                (d, v) -> d.setNote(v));

        final XKey<LocalDateTime> created = keyFactory.newKey(
                (d) -> d.getCreated(),
                (d, v) -> d.setCreated(v));

        @Override
        public KeyFactory<T> getKeyFactory() {
            return keyFactory;
        }
    };

    public _Order() {
        super(new DirectKeys());
    }

    public _Order(@Nullable final Key<D, ?> keyPrefix, @Nonnull final DirectKeyRing directKeyRing, final boolean descending) {
        super(keyPrefix, directKeyRing, descending);
    }

    @Override
    public <A> AbstractDomainModel<A, Order> prefix(Key<A, D> key) {
        return new _Order(key, directKeys(), false);
    }

    @Override
    public D createDomain() {
        return (D) new Order();
    }

    @Override
    protected final DirectKeys directKeys() {
        return (DirectKeys) directKeyRing;
    }

    // --- KEY PROVIDERS ---

    public Key<D, Integer> id() {
        return getKey(directKeys().id);
    }

    public Key<D, State> state() {
        return getKey(directKeys().state);
    }

    public  Key<D, BigDecimal> totalPrice() {
        return getKey(directKeys().totalPrice);
    }

    public _User<D> user() {
        return (_User) getKey(directKeys().user);
    }

    public Key<D, String> note() {
        return getKey(directKeys().note);
    }

    public Key<D, LocalDateTime> created() {
        return getKey(directKeys().created);
    }

}
