package org.ujorm2.metamodel;

import java.time.LocalDateTime;
import javax.annotation.Nullable;
import org.ujorm2.Key;
import org.ujorm2.core.KeyFactory;
import org.ujorm2.core.KeyImpl;
import org.ujorm2.core.MetaInterface;
import org.ujorm2.core.UjoContext;
import org.ujorm2.doman.Anonymous;
import org.ujorm2.doman.Item;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class MetaAnonymous<D> extends KeyImpl<D, Anonymous> implements MetaInterface<D> {

    /** All direct keys */
    protected static final class DirectKey<D> {

        final KeyFactory<Anonymous> keyFactory = new KeyFactory(Anonymous.class);

        final Key<Anonymous, Integer> id = keyFactory.newKey(
                (d) -> d.getId(),
                (d, v) -> d.setId(v));

        final Key<Anonymous, Short> pin = keyFactory.newKey(
                (d) -> d.getPin(),
                (d, v) -> d.setPin(v));

        final Key<Anonymous, LocalDateTime> created = keyFactory.newKey(
                (d) -> d.getCreated(),
                (d, v) -> d.setCreated(v));

        final MetaAnonymous<Anonymous> parent = keyFactory.newRelation(
                (d) -> d.getParent(),
                (d, v) -> d.setParent(v));

        public DirectKey() {
            keyFactory.close();
        }
    };

    /** All direct keys */
    private final DirectKey key = new DirectKey();

    public MetaAnonymous(UjoContext context) {
        super(Anonymous.class, context, null);
    }

    public MetaAnonymous(@Nullable Key<D,?> keyPrefix, UjoContext context) {
        super(keyPrefix.getDomainClass(), context, keyPrefix);
    }

    @Override
    public D createDomain() {
        return (D) new Item();
    }

    // --- KEY PROVIDERS ---

    public Key<D, Integer> id() {
        return getKey(key.id);
    }

    public Key<D, Short> pin() {
        return getKey(key.pin);
    }

    public Key<D, LocalDateTime> created() {
        return getKey(key.created);
    }

    public MetaAnonymous<D> parent() {
        return (MetaAnonymous) getKey(key.parent);
    }

    public static final MetaAnonymous<Anonymous> of(@Nullable UjoContext context) {
        return context.getMetaModel(Anonymous.class, MetaAnonymous.class);
    }

    public static final MetaAnonymous<Anonymous> of() {
        return of(UjoContext.of());
    }

}
