package org.ujorm2.metamodel;

import java.time.LocalDateTime;
import javax.annotation.Nullable;
import org.ujorm2.Key;
import org.ujorm2.core.AbstractDomainModel;
import org.ujorm2.core.KeyFactory;
import org.ujorm2.core.KeyFactoryProvider;
import org.ujorm2.core.UjoContext;
import org.ujorm2.doman.Item;
import org.ujorm2.doman.User;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class MetaUser<D> extends AbstractDomainModel<D, User> {

    /** All direct keys */
    static final class DirectKeys<T extends User> implements KeyFactoryProvider<T> {

        final KeyFactory<T> keyFactory = new KeyFactory(User.class);

        final Key<T, Integer> id = keyFactory.newKey(
                (d) -> d.getId(),
                (d, v) -> d.setId(v));

        final Key<T, Short> pin = keyFactory.newKey(
                (d) -> d.getPin(),
                (d, v) -> d.setPin(v));

        final Key<T, String> firstName = keyFactory.newKey(
                (d) -> d.getFirstName(),
                (d, v) -> d.setFirstName(v));

        final MetaOrder<T> sureName = keyFactory.newRelation(
                (d) -> d.getSureName(),
                (d, v) -> d.setSureName(v));

        final Key<T, LocalDateTime> born = keyFactory.newKey(
                (d) -> d.getBorn(),
                (d, v) -> d.setBorn(v));

        final MetaUser<T> parent = keyFactory.newRelation(
                (d) -> d.getParent(),
                (d, v) -> d.setParent(v));

        @Override
        public KeyFactory<T> getKeyFactory() {
            return keyFactory;
        }
    };

    public MetaUser() {
        super(new DirectKeys());
    }

    public MetaUser(KeyFactoryProvider keyFactoryProvider, Key<D, ?> keyPrefix) {
        super(keyFactoryProvider, keyPrefix);
    }

    @Override
    public <A> AbstractDomainModel<A, User> prefix(Key<A, D> key) {
        return new MetaUser(keys(), key);
    }

    @Override
    public D createDomain() {
        return (D) new Item();
    }

    @Override
    protected final DirectKeys keys() {
       return (DirectKeys) directKeys;
    }

    // --- KEY PROVIDERS ---

    public Key<D, Integer> id() {
        return getKey(keys().id);
    }

    public Key<D, Short> pin() {
        return getKey(keys().pin);
    }

    public Key<D, String> firstName() {
        return getKey(keys().firstName);
    }

    public Key<D, String> sureName() {
        return getKey(keys().sureName);
    }

    public Key<D, LocalDateTime> born() {
        return getKey(keys().born);
    }

    public MetaUser<D> parent() {
        return (MetaUser) getKey(keys().parent);
    }

    public static final MetaUser<User> of(@Nullable UjoContext context) {
        return new MetaUser<>();
    }
}
