package org.ujorm2.metamodel;

import java.math.BigDecimal;
import javax.annotation.Nullable;
import org.ujorm2.Key;
import org.ujorm2.core.KeyFactory;
import org.ujorm2.core.KeyImpl;
import org.ujorm2.core.MetaInterface;
import org.ujorm2.core.UjoContext;
import org.ujorm2.doman.Item;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class MetaItem<D> extends KeyImpl<D, Item> implements MetaInterface<D> {

    /** All direct keys */
    private static final class DirectKey<D> {

        final KeyFactory<Item> keyFactory = new KeyFactory(Item.class);

        final Key<Item, Integer> id = keyFactory.newKey("id",
                (d) -> d.getId(),
                (d, v) -> d.setId(v));

        final Key<Item, String> note = keyFactory.newKey("note",
                (d) -> d.getNote(),
                (d, v) -> d.setNote(v));

        final Key<Item, BigDecimal> price = keyFactory.newKey("price",
                (d) -> d.getPrice(),
                (d, v) -> d.setPrice(v));

        final MetaOrder<Item> order = keyFactory.newRelation("order",
                (d) -> d.getOrder(),
                (d, v) -> d.setOrder(v));

        final Key<Item, Boolean> descending = keyFactory.newKey("descending",
                (d) -> d.getDescending(),
                (d, v) -> d.setDescending(v));

        final Key<Item, Integer> codePoints = keyFactory.newKey("codePoints",
                (d) -> d.getCodePoints(),
                (d, v) -> d.setCodePoints(v));
    };

    private final DirectKey key = new DirectKey();

    public MetaItem(Class<D> domainClass, UjoContext context) {
        super(domainClass, context);
    }

    // --- KEY PROVIDERS ---

    public Key<D, Integer> id() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (Key) key.id;
        } else {
            throw new IllegalStateException();
        }
    }

    public Key<D, String> note() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (Key) key.note;
        } else {
            throw new IllegalStateException();
        }
    }

    public Key<D, BigDecimal> price() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (Key) key.price;
        } else {
            throw new IllegalStateException();
        }
    }

    public MetaOrder<D> order() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (MetaOrder) key.order;
        } else {
            throw new IllegalStateException();
        }
    }

    public Key<D, Boolean> descending$() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (Key) key.descending;
        } else {
            throw new IllegalStateException();
        }
    }

    public Key<D, Integer> codePoints$() {
        if (getDomainClass().isAssignableFrom(key.keyFactory.getDomainClass())) {
            return (Key) key.codePoints;
        } else {
            throw new IllegalStateException();
        }
    }

    // ---- Helper method

    @Override
    public D createDomain() {
        return (D) new Item();
    }

    public static final MetaItem<Item> of(@Nullable UjoContext context) {
        return context.getMetaModel(Item.class, MetaItem.class);
    }

    public static final MetaItem<Item> of() {
        return of(UjoContext.of());
    }


}
