/*
 *  Copyright 2020-2020 Pavel Ponec
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */
package org.ujorm2.metamodel;

import javax.annotation.Nonnull;
import org.ujorm2.core.DomainItem;
import org.ujorm2.core.MetaDomainStore;
import org.ujorm2.core.UjoContext;
import org.ujorm2.doman.Anonymous;
import org.ujorm2.doman.Item;
import org.ujorm2.doman.Order;
import org.ujorm2.doman.User;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class ModelProvider extends UjoContext {

    final MetaDomainStore factory = new MetaDomainStore(ModelProvider.class);
    final DomainItem<MetaItem> item = factory.newModel();
    final DomainItem<MetaOrder> order = factory.newModel();
    final DomainItem<MetaUser> user = factory.newModel();
    final DomainItem<MetaAnonymous> anonumous = factory.newModel();

    public ModelProvider() {
        save(factory); // !
    }

    /** provide  */
    @Nonnull
    public MetaDomainStore getModels$() {
        return factory;
    }

    public MetaItem<Item> item() {
        return item.model();
    }

    public MetaOrder<Order> order() {
        return order.model();
    }

    public MetaUser<User> user() {
        return user.model();
    }

    public MetaAnonymous<Anonymous> anonumous() {
        return anonumous.model();
    }
}
