package org.ujorm2.metamodel;

import javax.annotation.Nonnull;
import org.ujorm2.core.MetaDomainStore;
import org.ujorm2.core.UjoContext;
import org.ujorm2.doman.Anonymous;
import org.ujorm2.doman.Item;
import org.ujorm2.doman.Order;
import org.ujorm2.doman.User;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public class ModelProvider extends UjoContext {

    final MetaDomainStore factory = new MetaDomainStore(ModelProvider.class);
    final MetaItem item = factory.newModel(new MetaItem());
    final MetaOrder order = factory.newModel(new MetaOrder());
    final MetaUser user = factory.newModel(new MetaUser());
    final MetaAnonymous anonumous = factory.newModel(new MetaAnonymous());

    public ModelProvider() {
        save(factory); // !
    }

    /** provide  */
    @Nonnull
    public MetaDomainStore getModels$() {
        return factory;
    }

    public MetaItem<Item> item() {
        return item;
    }

    public MetaOrder<Order> order() {
        return order;
    }

    public MetaUser<User> user() {
        return user;
    }

    public MetaAnonymous<Anonymous> anonumous() {
        return anonumous;
    }

}
