/*
 *  Copyright 2020-2020 Pavel Ponec
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */
package org.ujorm2.metamodel;

import org.ujorm2.core.MDomain;
import org.ujorm2.core.ModelProvider;
import org.ujorm2.doman.Anonymous;
import org.ujorm2.doman.Item;
import org.ujorm2.doman.Order;
import org.ujorm2.doman.User;

/**
 * TODO: A helper class generated by a Maven module.
 * @author Pavel Ponec
 */
public final class ModelContext {

    final ModelProvider provider = new ModelProvider();
    final MDomain<MetaItem> item = provider.newModel();
    final MDomain<MetaOrder> order = provider.newModel();
    final MDomain<MetaUser> user = provider.newModel();
    final MDomain<MetaAnonymous> anonumous = provider.newModel();

    public ModelContext() {
        provider.close(this);
    }

    /** Provides an extended API */
    public ModelProvider.Tools getTool$() {
        return provider.getTools();
    }

    public MetaItem<Item> item() {
        return item.get();
    }

    public MetaOrder<Order> order() {
        return order.get();
    }

    public MetaUser<User> user() {
        return user.get();
    }

    public MetaAnonymous<Anonymous> anonumous() {
        return anonumous.get();
    }
}
