/*
 *  Copyright 2014-2014 Pavel Ponec
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.ujorm.core;

import java.util.HashSet;
import java.util.Set;

/**
 * XML header
 * @author Pavel Ponec
 */
public class XmlHeader {

    /** XML header */
    public String header = UjoManagerXML.XML_HEADER;
    /** Description */
    public String description = "Generated by the module 'ujo-xsd' " + UjoManager.version();
    /** The root element name, the default name is {@code "body"} */
    public String rootElement;
    /** The root tag attributes */
    public Set attributes;

    public XmlHeader() {
        this("body");
    }

    public XmlHeader(String rootElement) {
        if (rootElement == null) {
            throw new IllegalArgumentException("Attribute is required");
        }
        this.rootElement = rootElement;
    }

    /**
     * The root tag name
     * @return the rootTag
     */
    public String getRootElement() {
        return rootElement;
    }

    /**
     * XML header
     * @return the header
     */
    public String getHeader() {
        return header;
    }

    /**
     * XML header
     * @param header the header to set
     */
    public void setHeader(String header) {
        this.header = header;
    }

    /**
     * Description
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Description
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * The root tag attributes
     * @return the not null result
     */
    public Set getAttributes() {
        if (attributes == null) {
            attributes = new HashSet();
        }
        return attributes;
    }
}
